### ISSUE TITLE
[Bug] opening a project file crashes Coollab

### ISSUE THREAD

**Issue by illtellyoulater** [CoolLibs/Lab#111]
### What happened?

Every time I try to open a saved project file Coollab creashes.

### Steps to reproduce

- Start Coollab
- File > Open > my-coollab-project.coollab
- Program crashes

### Coollab version or commit id

Coollab Beta 19 WIP (locally built)
(Ubuntu 22.04)

### Relevant log output

Segmentation fault (core dump created)

**Comment by illtellyoulater** [comment]
Workaround: using keyboard combination `<ctrl-o>` to open a project avoids the crash.

**Comment by JulesFouchy** [comment]
Hi, and thanks for reporting! I'll be able to check on my Ubuntu PC tomorrow ;)

**Comment by JulesFouchy** [comment]
Thanks for the investigation, noticing that the crash occurred when using the menu but not when using the shortcut helped me fix it !
