### ISSUE TITLE
[Bug] creating a new project file crashes Coollab

### ISSUE THREAD

**Issue by illtellyoulater** [CoolLibs/Lab#112]
### What happened?

Attempting to create a new project using File menu crashes Coollab.

### Steps to reproduce

- Start Coollab
- File > New
- Program crashes

### Coollab version or commit id

Coollab Beta 19 WIP (locally built)
(Ubuntu 22.04)

### Relevant log output

Segmentation fault (core dump created)

**Comment by illtellyoulater** [comment]
Workaround: using keyboard combination `<ctrl-n>` to create the project avoids the crash.

**Comment by JulesFouchy** [comment]
Hi, and thanks for reporting! I'll be able to check on my Ubuntu PC tomorrow ;)

**Comment by JulesFouchy** [comment]
Thanks for the investigation, noticing that the crash occurred when using the menu but not when using the shortcut helped me fix it !
